### PR TITLE
Tweaked nav bar, added spacing, adjusted cards

### PR DESCRIPTION
**Pull request by aubristahl**
**note: I commented out the style tags in TutorCard.vue and changed the cards through app.css.

### CODE REVIEW

**Comment by johnkuefler** [comment]
@aubristahl does this all look right? 
image

**Comment by aubristahl** [comment]
> @aubristahl does this all look right?
> image

Yep! Looks right to me.  Not quite finished with it.

**Comment by johnkuefler** [comment]
Cool, looking good! Just let me know when you've pushed your final set of changes to this branch and I'll merge it in.

**Comment by Lydia-Winters** [comment]
@aubristahl  I have made quite a few changes to tutor card. It may be best for you to make a note of the changes you made and discard your pull request and pull from master so we don't have as many merge conflicts.

**Comment by aubristahl** [comment]
> @aubristahl I have made quite a few changes to tutor card. It may be best for you to make a note of the changes you made and discard your pull request and pull from master so we don't have as many merge conflicts.

It's now not letting me pull from master because of an unfinished merge. (I assume it's this one)
@johnkuefler can you decline my pull request to see if I can pull a fresh version from master?

**Comment by johnkuefler** [comment]
@aubristahl  Yeah I can close this PR. You'll have to like discard your local changes or something I think... then switch to master and attempt to pull.

**Pull request closed without merging**
